<a href="https://colab.research.google.com/github/NileeshaDM/Google-Colabs/blob/main/Next_word_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


##Data Preparation

In [ ]:
%cd "/content/drive/MyDrive/Assignment2/"

doc = "Sequential_Dataset.txt"
text = open(doc, 'r', encoding='utf-8').read()
text = text.lower()

/content/drive/MyDrive/Assignment2


In [ ]:
text

'the outer most layer of earth is often referred to as the biosphere. the biosphere is the layer of living organisms that cover the surface of the planet and it readily distinguishes the planet from all others in the solar system ("biosphere", 2003). due to its flowing water and oxygen, earth is the only planet in the galaxy that is naturally habitable by humans. it is estimated that life has existed on earth for 3.5 to 4 billion years.\n\nthe earth\'s surface developed much like the other planets in the galaxy, through four major geological processes. the first process is known as impact cratering. impact craters are the result of comets or asteroids impacting with the surface of a planet. second, is the process known as volcanism. volcanism is the result of molten rock and lava spewing from the earth\'s interior to its surface. third, is the process of tectonics. tectonics is the disruption of a planet\'s surface by internal stresses. fourth and finally is the process of erosion. ero

In [ ]:
# create mapping of unique chars to integers
chars = sorted(list(set(text)))
char_to_int = dict((c, i) for i, c in enumerate (chars))
print(char_to_int)

{'\n': 0, ' ': 1, '"': 2, "'": 3, '(': 4, ')': 5, ',': 6, '.': 7, '0': 8, '2': 9, '3': 10, '4': 11, '5': 12, 'a': 13, 'b': 14, 'c': 15, 'd': 16, 'e': 17, 'f': 18, 'g': 19, 'h': 20, 'i': 21, 'j': 22, 'k': 23, 'l': 24, 'm': 25, 'n': 26, 'o': 27, 'p': 28, 'r': 29, 's': 30, 't': 31, 'u': 32, 'v': 33, 'w': 34, 'x': 35, 'y': 36}


In [ ]:
n_chars = len(text)
n_vocab= len(chars)
print("Total Characters: ", n_chars)
print("Total Vocab (Unique characters): ", n_vocab)

Total Characters:  1579
Total Vocab (Unique characters):  37


In [ ]:
#prepare the dataset of input to output pairs encoded as integers
seq_length = 20
dataX = []
dataY = []
for i in range(0, n_chars - seq_length, 1):
  seq_in = text[i:i + seq_length]
  seq_out = text[i + seq_length]
  dataX.append([char_to_int[char] for char in seq_in])
  dataY.append(char_to_int[seq_out])
n_patterns = len(dataY)
print("Total Patterns: ", n_patterns)

Total Patterns:  1559


In [ ]:
dataX

[[31, 20, 17, 1, 27, 32, 31, 17, 29, 1, 25, 27, 30, 31, 1, 24, 13, 36, 17, 29],
 [20, 17, 1, 27, 32, 31, 17, 29, 1, 25, 27, 30, 31, 1, 24, 13, 36, 17, 29, 1],
 [17, 1, 27, 32, 31, 17, 29, 1, 25, 27, 30, 31, 1, 24, 13, 36, 17, 29, 1, 27],
 [1, 27, 32, 31, 17, 29, 1, 25, 27, 30, 31, 1, 24, 13, 36, 17, 29, 1, 27, 18],
 [27, 32, 31, 17, 29, 1, 25, 27, 30, 31, 1, 24, 13, 36, 17, 29, 1, 27, 18, 1],
 [32, 31, 17, 29, 1, 25, 27, 30, 31, 1, 24, 13, 36, 17, 29, 1, 27, 18, 1, 17],
 [31, 17, 29, 1, 25, 27, 30, 31, 1, 24, 13, 36, 17, 29, 1, 27, 18, 1, 17, 13],
 [17, 29, 1, 25, 27, 30, 31, 1, 24, 13, 36, 17, 29, 1, 27, 18, 1, 17, 13, 29],
 [29, 1, 25, 27, 30, 31, 1, 24, 13, 36, 17, 29, 1, 27, 18, 1, 17, 13, 29, 31],
 [1, 25, 27, 30, 31, 1, 24, 13, 36, 17, 29, 1, 27, 18, 1, 17, 13, 29, 31, 20],
 [25, 27, 30, 31, 1, 24, 13, 36, 17, 29, 1, 27, 18, 1, 17, 13, 29, 31, 20, 1],
 [27, 30, 31, 1, 24, 13, 36, 17, 29, 1, 27, 18, 1, 17, 13, 29, 31, 20, 1, 21],
 [30, 31, 1, 24, 13, 36, 17, 29, 1, 27, 18, 1, 17, 

In [ ]:
dataY

[1,
 27,
 18,
 1,
 17,
 13,
 29,
 31,
 20,
 1,
 21,
 30,
 1,
 27,
 18,
 31,
 17,
 26,
 1,
 29,
 17,
 18,
 17,
 29,
 29,
 17,
 16,
 1,
 31,
 27,
 1,
 13,
 30,
 1,
 31,
 20,
 17,
 1,
 14,
 21,
 27,
 30,
 28,
 20,
 17,
 29,
 17,
 7,
 1,
 31,
 20,
 17,
 1,
 14,
 21,
 27,
 30,
 28,
 20,
 17,
 29,
 17,
 1,
 21,
 30,
 1,
 31,
 20,
 17,
 1,
 24,
 13,
 36,
 17,
 29,
 1,
 27,
 18,
 1,
 24,
 21,
 33,
 21,
 26,
 19,
 1,
 27,
 29,
 19,
 13,
 26,
 21,
 30,
 25,
 30,
 1,
 31,
 20,
 13,
 31,
 1,
 15,
 27,
 33,
 17,
 29,
 1,
 31,
 20,
 17,
 1,
 30,
 32,
 29,
 18,
 13,
 15,
 17,
 1,
 27,
 18,
 1,
 31,
 20,
 17,
 1,
 28,
 24,
 13,
 26,
 17,
 31,
 1,
 13,
 26,
 16,
 1,
 21,
 31,
 1,
 29,
 17,
 13,
 16,
 21,
 24,
 36,
 1,
 16,
 21,
 30,
 31,
 21,
 26,
 19,
 32,
 21,
 30,
 20,
 17,
 30,
 1,
 31,
 20,
 17,
 1,
 28,
 24,
 13,
 26,
 17,
 31,
 1,
 18,
 29,
 27,
 25,
 1,
 13,
 24,
 24,
 1,
 27,
 31,
 20,
 17,
 29,
 30,
 1,
 21,
 26,
 1,
 31,
 20,
 17,
 1,
 30,
 27,
 24,
 13,
 29,
 1,
 30,
 36,
 30,
 31,
 17,
 25

In [ ]:
import numpy
# reshape X to be [samples, time steps, features]
X = numpy.reshape(dataX, (n_patterns, seq_length, 1))

# normalize - rescaling the integer values
X = X / float(n_vocab)
print(X)

[[[0.83783784]
  [0.54054054]
  [0.45945946]
  ...
  [0.97297297]
  [0.45945946]
  [0.78378378]]

 [[0.54054054]
  [0.45945946]
  [0.02702703]
  ...
  [0.45945946]
  [0.78378378]
  [0.02702703]]

 [[0.45945946]
  [0.02702703]
  [0.72972973]
  ...
  [0.78378378]
  [0.02702703]
  [0.72972973]]

 ...

 [[0.83783784]
  [0.16216216]
  [0.02702703]
  ...
  [0.02702703]
  [0.24324324]
  [0.27027027]]

 [[0.16216216]
  [0.02702703]
  [0.59459459]
  ...
  [0.24324324]
  [0.27027027]
  [0.21621622]]

 [[0.02702703]
  [0.59459459]
  [0.18918919]
  ...
  [0.27027027]
  [0.21621622]
  [0.13513514]]]


##Model Design

In [ ]:
import tensorflow as tf
from tensorflow import keras
from keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.callbacks import ModelCheckpoint

In [ ]:
# one hot encode the output variable
y= to_categorical(dataY)
y

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [ ]:
# define the LSTM model
model = Sequential()
model.add(LSTM(7, input_shape=(X.shape[1], X.shape[2])))
model.add(Dropout(0.2))
model.add(Dense(y.shape[1], activation="softmax"))
model.compile(loss= "categorical_crossentropy", optimizer="adam")
# define the checkpoint
filepath ="weights-improvement-{epoch:02d}-{loss:.4F}.hdfs"
checkpoint = ModelCheckpoint(filepath, monitor ="loss", verbose=1, save_best_only=True, mode="min")
callbacks_list = [checkpoint]

##Training

In [ ]:
epochs = 15
batch_size=  150
model.fit(X, y, epochs=epochs, batch_size=batch_size, callbacks=callbacks_list)

Epoch 1/15
 1/11 [=>............................] - ETA: 26s - loss: 3.6320
Epoch 1: loss improved from inf to 3.61364, saving model to weights-improvement-01-3.6136.hdfs
11/11 [==============================] - 6s 303ms/step - loss: 3.6136
Epoch 2/15
 1/11 [=>............................] - ETA: 0s - loss: 3.5911
Epoch 2: loss improved from 3.61364 to 3.58097, saving model to weights-improvement-02-3.5810.hdfs
11/11 [==============================] - 3s 299ms/step - loss: 3.5810
Epoch 3/15
10/11 [==========================>...] - ETA: 0s - loss: 3.5535
Epoch 3: loss improved from 3.58097 to 3.55348, saving model to weights-improvement-03-3.5535.hdfs
11/11 [==============================] - 4s 419ms/step - loss: 3.5535
Epoch 4/15
 1/11 [=>............................] - ETA: 0s - loss: 3.5437
Epoch 4: loss improved from 3.55348 to 3.52399, saving model to weights-improvement-04-3.5240.hdfs
11/11 [==============================] - 3s 294ms/step - loss: 3.5240
Epoch 5/15
10/11 [=========

##Evaluation

In [ ]:
#load the network weights
file_weight="weights-improvement-06-3.4506.hdfs"
model.load_weights (file_weight)
model.compile(loss="categorical_crossentropy", optimizer="adam")

int_to_char = {i:char for i, char in enumerate(chars)}

# generate a random seed
print("Size of DataX:", len(dataX))
start = numpy.random.randint(0, len(dataX)-1)
print("Start from:", start)
pattern = dataX[start]
print("Seed:")
sentence = [int_to_char[value] for value in pattern]
print("\"", ''.join(sentence), "\"")

Size of DataX: 1559
Start from: 1464
Seed:
" lithosphere graduall "


In [ ]:
length = 5
final = []
for i in range(length):
    x = numpy.reshape(pattern, (1, len(pattern), 1))
    x = x / float(n_vocab)
    prediction = model.predict(x, verbose=0)

    # Get the predicted values with the highest probabilities
    indices = numpy.argsort(prediction[0])[-1:]

    # Convert the indices to characters and join
    results = [int_to_char[index] for index in indices]
    final.append(''.join(results))

    # Update the pattern with both predicted indices
    pattern.extend(indices)

    # Remove the first characters from the seed sequence
    pattern = pattern[1:len(pattern)]
print(final)

['e', 'e', 'e', 'e', 'e']


In [ ]:
for i in final:
  sentence.append(i)
print(sentence)

['l', 'i', 't', 'h', 'o', 's', 'p', 'h', 'e', 'r', 'e', ' ', 'g', 'r', 'a', 'd', 'u', 'a', 'l', 'l', 'e', 'e', 'e', 'e', 'e']


In [ ]:
# print whole sequence
sentence = "".join(sentence)
print("Sequence: ",sentence)

Sequence:  lithosphere gradualleeeee
